---
- name: Load contact_roles var file
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/contact_roles.yml"
  when: contact_roles is not defined

- name: Ensure contact roles exist
  netbox.netbox.netbox_contact_role:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_token }}"
    validate_certs: "{{ netbox_validate_certs }}"
    data: "{{ item }}"
    state: present
  loop: "{{ contact_roles | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
