---
- name: Load rirs var file
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/rirs.yml"
  when: rirs is not defined

- name: Ensure rirs exist
  netbox.netbox.netbox_rir:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_token }}"
    validate_certs: "{{ netbox_validate_certs }}"
    data: "{{ item }}"
    state: present
  loop: "{{ rirs | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
