---
- name: Load vlan_groups var file
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/vlan_groups.yml"
  when: vlan_groups is not defined

- name: Ensure vlan_groups exist
  netbox.netbox.netbox_vlan_group:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_token }}"
    validate_certs: "{{ netbox_validate_certs }}"
    data: "{{ item }}"
    state: present
  loop: "{{ vlan_groups | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
